apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: {{ .Values.global.base_namespace }}
spec:
  selector:
    app-name: backend
  ports:
    - protocol: TCP
      port: 5000
      name: backend-http
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: backend-strip-prefix
  namespace: {{ .Values.global.base_namespace }}
spec:
  stripPrefix:
    prefixes:
      - /{{ .Values.global.path_prefix }}
      - /{{ .Values.global.path_prefix }}/
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: {{ .Values.global.base_namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-errorpages@kubernetescrd,{{ .Values.global.base_namespace }}-backend-strip-prefix@kubernetescrd
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
  - host: 
    http:
      paths:
      - path: /{{ .Values.global.path_prefix }}
        backend:
          serviceName: backend-service
          servicePort: backend-http
